### ISSUE TITLE
Ilias startup throws error: Could not open input file: setup/cli.php

### ISSUE THREAD

**Issue by Lars2206** [srsolutionsag/docker-ilias-base#4]
started ilias container with compose.yaml:

```
services:
    ilias:
        image: srsolutions/ilias
        ports:
          - 8080:80
        links:
          - mysql
        environment:
          - ILIAS_AUTO_SETUP=1
          - ILIAS_DB_USER=root
          - ILIAS_DB_PASSWORD=example1!
        volumes:
          - "./shared/ilias:/var/"
    mysql:
        image: mysql:5.7
        command: |
            --character-set-server=utf8
            --collation-server=utf8_general_ci
            --max-allowed-packet=32M
            --default_authentication_plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=example1!
          - MYSQL_DATABASE=ilias
        volumes:
          - "./shared/db:/var/lib/mysql"

```
but after db init ilias throws error: Could not open input file: setup/cli.php

[iias-error.txt](https://github.com/user-attachments/files/19040662/iias-error.txt)

**Comment by corro** [comment]
The image assumes that the ILIAS source code is available under `/var/www/html`. Maybe the volume you mount at `/var` has a different directory structure?
```
services:
    ilias:
        [...]
        volumes:
          - "./shared/ilias:/var/"
```
